In [1]:
import numpy as np

In [2]:
arr = np.random.rand(5,5)

In [3]:
print(arr+10)
print(arr-10)
print(arr*10)
print(arr/10)

[[10.61796097 10.67193616 10.80438027 10.92380656 10.97297291]
 [10.80150932 10.77125163 10.67361733 10.14622632 10.88223263]
 [10.58181669 10.31298261 10.01692884 10.20471832 10.01316235]
 [10.53746395 10.14268875 10.98438572 10.91102588 10.77816703]
 [10.97588187 10.24355781 10.42899085 10.75856861 10.35639612]]
[[-9.38203903 -9.32806384 -9.19561973 -9.07619344 -9.02702709]
 [-9.19849068 -9.22874837 -9.32638267 -9.85377368 -9.11776737]
 [-9.41818331 -9.68701739 -9.98307116 -9.79528168 -9.98683765]
 [-9.46253605 -9.85731125 -9.01561428 -9.08897412 -9.22183297]
 [-9.02411813 -9.75644219 -9.57100915 -9.24143139 -9.64360388]]
[[6.17960974 6.71936157 8.04380275 9.23806556 9.7297291 ]
 [8.01509317 7.71251633 6.73617334 1.46226324 8.82232632]
 [5.81816691 3.12982613 0.16928836 2.04718322 0.13162353]
 [5.37463947 1.42688749 9.84385724 9.11025877 7.78167029]
 [9.75881874 2.4355781  4.28990853 7.58568613 3.56396117]]
[[0.0617961  0.06719362 0.08043803 0.09238066 0.09729729]
 [0.08015093 0.0771

In [6]:
arr1 = np.array([1,2,3])
np.add(arr1,[6,7,8], out = arr1)
print(arr1)
np.subtract(arr1,[8,9,10],out=arr1)
print(arr1)
np.multiply(arr1,[1,2,3],out=arr1)
print(arr1)

[ 7  9 11]
[-1  0  1]
[-1  0  3]


In [7]:
print(np.exp(arr))

[[1.8551415  1.9580247  2.23531079 2.51886035 2.6457985 ]
 [2.22890251 2.16247118 1.96131925 1.15745812 2.41628837]
 [1.78928606 1.36749775 1.01707294 1.22717935 1.01324936]
 [1.71166049 1.15337076 2.67616747 2.48687245 2.17747735]
 [2.65350624 1.27578007 1.53570699 2.13521771 1.42817316]]


In [8]:
print(np.log(arr))

[[-0.48132997 -0.39759195 -0.21768314 -0.07925258 -0.02739904]
 [-0.22125868 -0.25974059 -0.39509308 -1.92259969 -0.1252995 ]
 [-0.54159984 -1.16160764 -4.07873686 -1.58612028 -4.33039458]
 [-0.6208936  -1.9470896  -0.01573746 -0.09318398 -0.25081409]
 [-0.02441373 -1.41240095 -0.84631968 -0.27632203 -1.03171248]]


In [9]:
print(np.log2(arr))

[[-0.69441236 -0.57360393 -0.31405039 -0.11433731 -0.03952846]
 [-0.3192088  -0.37472646 -0.56999883 -2.77372504 -0.18076897]
 [-0.78136341 -1.67584558 -5.88437344 -2.28828787 -6.24743879]
 [-0.89576011 -2.80905651 -0.02270436 -0.13443606 -0.36184824]
 [-0.03522157 -2.03766385 -1.22098121 -0.39864842 -1.48844648]]


In [10]:
print(np.log10(arr))

[[-0.20903895 -0.17267199 -0.09453859 -0.03441896 -0.01189925]
 [-0.09609142 -0.1128039  -0.17158675 -0.83497444 -0.05441688]
 [-0.23521382 -0.50447979 -1.77137291 -0.68884329 -1.88066647]
 [-0.26965066 -0.84561027 -0.00683469 -0.04046929 -0.10892717]
 [-0.01060275 -0.61339794 -0.36755197 -0.12000513 -0.44806704]]


In [11]:
print(np.sqrt(arr))

[[0.78610494 0.81971712 0.8968725  0.96114856 0.98639389]
 [0.89527053 0.87820933 0.82074194 0.38239551 0.93927239]
 [0.76276909 0.55944849 0.13011086 0.45245809 0.1147273 ]
 [0.73311933 0.37774164 0.99216215 0.95447676 0.88213776]
 [0.98786734 0.49351577 0.65497393 0.87095844 0.59698921]]


In [12]:
print(np.sin(arr))

[[0.57937443 0.62250242 0.72040097 0.79790194 0.82656265]
 [0.71840682 0.69703325 0.62381726 0.14570578 0.77215948]
 [0.54954263 0.30789772 0.01692803 0.20329137 0.01316197]
 [0.51195915 0.14220505 0.83293232 0.79013295 0.70197515]
 [0.82819645 0.24115695 0.41595331 0.68788322 0.34889909]]


In [14]:
print(np.cos(arr))

[[0.81506151 0.78261787 0.69355782 0.60278727 0.56284473]
 [0.6956232  0.7170388  0.78157023 0.98932797 0.63542878]
 [0.83546568 0.95141946 0.99985671 0.97911829 0.99991338]
 [0.8590098  0.98983722 0.55337487 0.61293549 0.71220143]
 [0.56043791 0.97048613 0.90938597 0.72582138 0.9371603 ]]


In [15]:
print(np.sum(arr, axis=0))

[3.5146328  2.14241696 2.90830302 2.94434569 3.00293104]


In [16]:
print(np.sum(arr, axis=1))

[3.99105687 3.27483724 1.12960881 3.35373133 2.76339527]


In [17]:
print(np.max(arr))

0.9843857243430008


In [18]:
print(np.min(arr))

0.013162352825361379


In [19]:
print(np.argmin(arr, axis=1))
print(np.argmax(arr, axis=1))

[0 3 4 1 1]
[4 4 0 2 0]


In [20]:
print(np.argmin(arr))
print(np.argmax(arr))

14
17


In [21]:
arr1 = np.array([1, 3, 5, 7, 9])
arr2 = np.array([0, 4, 3, 8, 7])
print(np.maximum(arr1, arr2))
print(np.minimum(arr1, arr2))

[1 4 5 8 9]
[0 3 3 7 7]


In [22]:
arr1 = np.random.rand(10) * 10
re, intg = np.modf(arr1)
print('fractional: ', re)
print('integral: ', intg)

fractional:  [0.46904469 0.80986919 0.64114033 0.44628919 0.38228313 0.8626671
 0.95519311 0.22779076 0.35543707 0.42682385]
integral:  [8. 4. 0. 0. 2. 0. 3. 1. 5. 6.]


In [23]:
print(np.mean(arr))

0.5805051807591648


In [24]:
print(np.mean(arr, axis = 0))

[0.70292656 0.42848339 0.5816606  0.58886914 0.60058621]


In [25]:
print(np.mean(arr, axis=1))

[0.79821137 0.65496745 0.22592176 0.67074627 0.55267905]


In [26]:
print(np.median(arr))

0.6719361568082981


In [27]:
print(np.median(arr, axis = 0))

[0.61796097 0.31298261 0.67361733 0.75856861 0.77816703]


In [28]:
print(np.median(arr, axis = 1))

[0.80438027 0.77125163 0.20471832 0.77816703 0.42899085]


In [29]:
arr1 = np.random.rand(100)
print(np.percentile(arr1,[1.4,5]))

[0.02577145 0.07152934]


In [30]:
print(np.std(arr))

0.31223706153821


In [31]:
print(np.var(arr))

0.09749198259801595


In [32]:
print(np.var(arr, axis = 0))

[0.02669756 0.06119516 0.11249553 0.11765409 0.13084542]


In [33]:
print(np.var(arr, axis = 1))

[0.01895789 0.06916227 0.044727   0.09285043 0.07417457]


In [34]:
arr = np.random.rand(5,10)

In [36]:
print(np.cov(arr))

[[ 0.09407014 -0.01435005  0.03241169 -0.02273354  0.068559  ]
 [-0.01435005  0.11667061 -0.06718683  0.0720076  -0.02429362]
 [ 0.03241169 -0.06718683  0.10627443 -0.01895748  0.0377766 ]
 [-0.02273354  0.0720076  -0.01895748  0.12019311 -0.01425255]
 [ 0.068559   -0.02429362  0.0377766  -0.01425255  0.08541144]]


In [37]:
print(np.corrcoef(arr[:,0], arr[:,1]))

[[1.         0.46461022]
 [0.46461022 1.        ]]


In [38]:
print(np.cumsum(arr, axis=0))

[[0.27892692 0.85790988 0.97738888 0.23887045 0.57057242 0.91097591
  0.27510312 0.70036051 0.28712271 0.90511485]
 [0.78669144 1.78342634 1.46546695 1.11538919 1.56935857 0.99718217
  0.33841202 1.48402102 0.95696251 1.1769236 ]
 [1.78097846 2.68102229 1.96956415 1.36814676 1.66503504 1.95339762
  1.03543663 1.90981211 1.26899634 2.05759598]
 [2.61230829 3.50086398 2.09649959 1.73148418 2.53051954 2.4588572
  1.05156813 2.52760162 2.26711604 2.25176017]
 [2.8147453  4.23597786 2.53111993 1.74702615 3.14332226 3.31846492
  1.54961881 3.19244759 2.31436752 2.89323244]]


In [39]:
print(np.cumsum(arr, axis=1))

[[0.27892692 1.1368368  2.11422568 2.35309612 2.92366854 3.83464446
  4.10974758 4.81010809 5.0972308  6.00234565]
 [0.50776452 1.43328099 1.92135906 2.7978778  3.79666395 3.88287021
  3.9461791  4.72983961 5.39967941 5.67148816]
 [0.99428702 1.89188297 2.39598016 2.64873773 2.74441419 3.70062964
  4.39765425 4.82344534 5.13547917 6.01615156]
 [0.83132983 1.65117151 1.77810696 2.14144438 3.00692889 3.51238847
  3.52851997 4.14630948 5.14442918 5.33859336]
 [0.20243701 0.93755089 1.37217123 1.38771319 2.00051591 2.86012364
  3.35817432 4.02302029 4.07027177 4.71174404]]


In [40]:
print(np.cumprod(arr, axis=0))

[[2.78926917e-01 8.57909880e-01 9.77388879e-01 2.38870446e-01
  5.70572423e-01 9.10975912e-01 2.75103124e-01 7.00360506e-01
  2.87122708e-01 9.05114853e-01]
 [1.41629193e-01 7.94009718e-01 4.77042083e-01 2.09374422e-01
  5.69879834e-01 7.85318219e-02 1.74164748e-02 5.48844871e-01
  1.92326218e-01 2.46018132e-01]
 [1.40820068e-01 7.12699905e-01 2.40475575e-01 5.29209708e-02
  5.45240861e-02 7.50933413e-02 1.21397115e-02 2.33693259e-01
  6.00122863e-02 2.16661375e-01]
 [1.17067923e-01 5.84301092e-01 3.05248738e-02 1.92281693e-02
  4.71897516e-02 3.79566489e-02 1.95831815e-04 1.44373244e-01
  5.98994449e-02 4.20678789e-02]
 [2.36988802e-02 4.29527843e-01 1.32667310e-02 2.98843548e-04
  2.89180082e-02 3.26278286e-02 9.75341686e-05 9.59859690e-02
  2.83033752e-03 2.69853779e-02]]


In [41]:
print(np.cumprod(arr, axis=1))

[[2.78926917e-01 2.39294158e-01 2.33883448e-01 5.58678437e-02
  3.18766509e-02 2.90388611e-02 7.98868143e-03 5.59495697e-03
  1.60643920e-03 1.45401198e-03]
 [5.07764524e-01 4.69944426e-01 2.29369571e-01 2.01046727e-01
  2.00802687e-01 1.73104477e-02 1.09590531e-03 8.58817714e-04
  5.75270287e-04 1.56363495e-04]
 [9.94287018e-01 8.92467998e-01 4.49890612e-01 1.13713259e-01
  1.08796823e-02 1.04033203e-02 7.25137022e-03 3.08756887e-03
  9.63425938e-04 8.48462619e-04]
 [8.31329828e-01 6.81558849e-01 8.65139750e-02 3.14337649e-02
  2.72054364e-02 1.37512485e-02 2.21828333e-04 1.37043217e-04
  1.36785534e-04 2.65588514e-05]
 [2.02437010e-01 1.48814255e-01 6.46777019e-02 1.00521863e-03
  6.16000709e-04 5.29518969e-04 2.63727282e-04 1.75338020e-04
  8.28498123e-06 5.31458574e-06]]


In [42]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

In [43]:
print(arr1 == arr2)
print(arr2 > 5)

[False False False False False]
[ True  True  True  True  True]
