In [1]:
import numpy as np

In [2]:
np.random.seed(123)

In [3]:
rs = np.random.RandomState(321)
rs.rand(10)

array([0.88594794, 0.07791236, 0.97964616, 0.24767146, 0.75288472,
       0.52667564, 0.90755375, 0.8840703 , 0.08926896, 0.5173446 ])

In [4]:
print(np.random.rand())

0.6964691855978616


In [5]:
print(np.random.rand(3))

[0.28613933 0.22685145 0.55131477]


In [6]:
print(np.random.randn(3,3))

[[-0.57860025  1.65143654 -2.42667924]
 [-0.42891263  1.26593626 -0.8667404 ]
 [-0.67888615 -0.09470897  1.49138963]]


In [7]:
print(np.random.randint(1, 10, 3, 'i8'))

[8 4 3]


In [8]:
print(np.random.random_sample(10))
print(np.random.random(10))
print(np.random.ranf(10))
print(np.random.sample(10))

[0.08372648 0.71233018 0.42786349 0.2977805  0.49208478 0.74029639
 0.35772892 0.41720995 0.65472131 0.37380143]
[0.23451288 0.98799529 0.76599595 0.77700444 0.02798196 0.17390652
 0.15408224 0.07708648 0.8898657  0.7503787 ]
[0.69340324 0.51176338 0.46426806 0.56843069 0.30254945 0.49730879
 0.68326291 0.91669867 0.10892895 0.49549179]
[0.23283593 0.43686066 0.75154299 0.48089213 0.79772841 0.28270293
 0.43341824 0.00975735 0.34079598 0.68927201]


In [9]:
print(np.random.choice(range(3), 10, replace=True, p=[0.1, 0.8, 0.1]))

[1 1 1 1 1 1 1 1 1 1]


In [10]:
print(np.random.choice(3, 10))

[2 0 2 2 1 1 2 2 0 1]


In [11]:
print(np.random.choice([1,2,3], 10))

[2 1 2 1 2 3 3 1 2 2]
