In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [3]:
arr = np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


In [4]:
arr = np.array(range(10))
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
arr = np.array([[1,2,3], [4,5,6]], dtype = 'i2')
print(arr)
print('Data type: ' + str(arr.dtype))

[[1 2 3]
 [4 5 6]]
Data type: int16


In [7]:
arr = np.arange(0, 20, 2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [9]:
arr, step_size = np.linspace(0,5,8, endpoint = False, retstep=True)
print(arr)
print('The step size is ' + str(step_size))

[0.    0.625 1.25  1.875 2.5   3.125 3.75  4.375]
The step size is 0.625


In [10]:
arr = np.random.rand(3,3)
print(arr)

[[0.35297069 0.65005677 0.50264917]
 [0.35673594 0.61546144 0.64569286]
 [0.07424096 0.83733387 0.35052944]]


In [12]:
zeros = np.zeros((10,10))
print(zeros)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [13]:
arr = np.array([[1,2], [3,4], [5,6]], dtype=np.complex64)
zeros = np.zeros_like(arr)
print(zeros)
print('Data Type: ' + str(zeros.dtype))

[[0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]]
Data Type: complex64


In [14]:
ones = np.ones((3,2))
print(ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [15]:
arr = [[1,2,3], [4,5,6]]
ones = np.ones_like(arr)
print(ones)
print('Data type: ' + str(ones.dtype))

[[1 1 1]
 [1 1 1]]
Data type: int32


In [16]:
empty = np.empty((5,5))
print(empty)

[[9.68834221e-312 7.60861095e-322 0.00000000e+000 0.00000000e+000
  7.56587583e-307]
 [1.16095484e-028 8.76381537e+252 1.28153217e-152 7.35167805e+223
  7.56455764e-096]
 [6.01409043e+175 2.17237424e-153 5.39223091e+241 5.39842349e+242
  8.82142681e+199]
 [9.24795351e+135 4.73517493e-120 2.66472736e+233 8.78414070e+247
  2.18174334e+243]
 [9.26807906e+199 1.47278596e+179 9.08367237e+223 1.16466228e-028
  3.93370719e-317]]


In [17]:
arr = np.array([[1,2,3],[4,5,6]], dtype=np.int64)
empty = np.empty_like(arr)
print(empty)
print('Data Type: '+ str(empty.dtype))

[[1065353216 1073741824 1077936128]
 [1082130432 1084227584 1086324736]]
Data Type: int64


In [18]:
full = np.full((4,4), 8)
print(full)

[[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]


In [20]:
arr = np.array([[1,2], [3,4]], dtype=np.float64)
full = np.full_like(arr, 5)
print(full)
print('Data Type: ' + str(full.dtype))

[[5. 5.]
 [5. 5.]]
Data Type: float64


In [21]:
arr = [[0,1,2],[3,4,5]]
print(np.repeat(arr, 3))

[0 0 0 1 1 1 2 2 2 3 3 3 4 4 4 5 5 5]


In [22]:
arr = [[0,1,2],[3,4,5]]
print(np.repeat(arr, 3, axis=0))

[[0 1 2]
 [0 1 2]
 [0 1 2]
 [3 4 5]
 [3 4 5]
 [3 4 5]]


In [24]:
arr = [[0,1,2],[3,4,5]]
print(np.repeat(arr, 3, axis = 1))

[[0 0 0 1 1 1 2 2 2]
 [3 3 3 4 4 4 5 5 5]]


In [26]:
arr = [0, 1, 2]
print(np.tile(arr,5))

[0 1 2 0 1 2 0 1 2 0 1 2 0 1 2]


In [27]:
print(np.tile(arr, (2,2)))

[[0 1 2 0 1 2]
 [0 1 2 0 1 2]]


In [28]:
identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [29]:
identity_matrix = np.eye(5, k=-1)
print(identity_matrix)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [32]:
identity_matrix = np.identity(6)
print(identity_matrix)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [33]:
arr = np.random.rand(5,5)
print(arr)

print('Values on the diagonal: '+ str(np.diag(arr)))

[[0.91635424 0.3683772  0.47333402 0.09671898 0.5879989 ]
 [0.44342544 0.62995887 0.30319086 0.53218355 0.23434279]
 [0.40107297 0.02218251 0.94190675 0.79790467 0.27546014]
 [0.93951686 0.82580446 0.68312612 0.05856735 0.86326954]
 [0.91710194 0.55053776 0.65750179 0.64330598 0.56610383]]
Values on the diagonal: [0.91635424 0.62995887 0.94190675 0.05856735 0.56610383]


In [34]:
arr = np.random.rand(10,3)
print(arr)

print('Values on the diagonal: ' + str(np.diag(arr)))

[[0.20498154 0.04363583 0.1745857 ]
 [0.45229893 0.77022214 0.95588272]
 [0.84002327 0.85492101 0.86641342]
 [0.07672266 0.98871295 0.05988607]
 [0.61302278 0.9285271  0.91595134]
 [0.92984627 0.63893533 0.84757828]
 [0.70468563 0.92798615 0.21831592]
 [0.63690395 0.09809896 0.78402702]
 [0.40135737 0.84183224 0.67711179]
 [0.54584955 0.18892864 0.31840358]]
Values on the diagonal: [0.20498154 0.77022214 0.86641342]


In [35]:
arr = np.diag([1,2,3,4,5])
print(arr)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
