In [1]:
import numpy as np

In [4]:
arr = np.array(range(100)). reshape(10,10)

In [5]:
print(arr[5][5])
print(arr[5,5])

55
55


In [6]:
print(arr[1:3,4:6])

[[14 15]
 [24 25]]


In [7]:
arr=np.array(range(16)).reshape(2,2,2,2)

In [8]:
print(arr[0,...])

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [9]:
arr[1:3,:] = 100
arr[:,8:] = 100
print(arr)

[[[[  0   1]
   [  2   3]]

  [[  4   5]
   [  6   7]]]


 [[[100 100]
   [100 100]]

  [[100 100]
   [100 100]]]]


In [10]:
arr1 = np.arange(25).reshape((5,5))
bools = np.array([True, True, False, True, False])
print(arr1[bools])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [15 16 17 18 19]]


In [11]:
print(arr1[~bools])

[[10 11 12 13 14]
 [20 21 22 23 24]]


In [12]:
arr2 = np.array([1,2,3,4,5])
print(arr1[(arr2<2) | (arr2>4)])

[[ 0  1  2  3  4]
 [20 21 22 23 24]]


In [13]:
arr = np.random.rand(10,10)

In [14]:
print(arr[[3,1,2], [3,2,1]])

[0.8011411  0.13813503 0.68850598]


In [15]:
print(arr[[3,1,2]][:, [6,4,8]])

[[0.25222537 0.4762217  0.4885632 ]
 [0.66925503 0.27935141 0.3711114 ]
 [0.17376152 0.04374134 0.29338695]]


In [18]:
arr = np.array(range(16)).reshape((4,-3))
print(arr.shape)

(4, 4)


In [19]:
arr = np.arange(16).reshape(4,4)

In [20]:
print(arr[arr>5])

[ 6  7  8  9 10 11 12 13 14 15]
